### ISSUE TITLE
testscript: how to ensure that tests are run when the scripts change?

### ISSUE THREAD

**Issue by twpayne** [rogpeppe/go-internal#100]
So opening this issue makes me a little bit sad because I know what the answer will be.

Right now, if you run `go test`, then add a new test failing script, and run `go test` again then `go test` will report success because it's using its cached test result. The `go` tool is clueless to changes outside its own world and still thinks that its cache is valid. There are only two hard problems in computer science, and we've already accepted Go's name.

Are there any ways to fix this? Specifically, I'm looking for a way to ensure that if my testscripts change then the tests get re-run.

One possibility might be somehow build on `go:generate` such that all the badness and weirdness is concentrated in one spot (i.e. have `testscript` generate Go code instead of executing from files in `testdata/` directly). Hopefully Cunningham's Law is true...

**Comment by myitcv** [comment]
> The go tool is clueless to changes outside its own world and still thinks that its cache is valid

I don't think that's always the case because of https://pkg.go.dev/internal/testlog?tab=doc.

Indeed:

```
# Test that adding a new failing testscript is detected

env GOCACHE=$WORK/gocache
cd blah

# Pre download to keep output that follows clean
go mod download

# First time around we should see no cache
go test .
! stdout '\(cached\)'

# Check we have a cached result second time around
go test .
stdout '\(cached\)'

# Now put the bad test in place
cp testdata/notok.txt_ testdata/notok.txt

# Check that we get a failing test
! go test .
stdout 'exit status 5'

-- blah/go.mod --
module mod.com

go 1.12

require github.com/rogpeppe/go-internal v1.6.0
-- blah/main.go --
package main

import "os"

func main() { os.Exit(ok()) }

func ok() int {
	return 0
}

func notok() int {
	return 5
}
-- blah/main_test.go --
package main

import (
	"os"
	"testing"

	"github.com/rogpeppe/go-internal/testscript"
)

func TestMain(m *testing.M) {
	os.Exit(testscript.RunMain(m, map[string]func() int{
		"ok":    ok,
		"notok": notok,
	}))
}

func TestFoo(t *testing.T) {
	testscript.Run(t, testscript.Params{
		Dir: "testdata",
	})
}
-- blah/testdata/notok.txt_ --
notok
-- blah/testdata/ok.txt --
ok
```

> Specifically, I'm looking for a way to ensure that if my testscripts change then the tests get re-run.

If the testscripts themselves change then I think you should always see a cache miss. Do you have a repro of where that's not happening?

**Comment by twpayne** [comment]
Ah, I see. Sorry this looks like a false alarm/error on my part. Thanks for the insight into `testlog`.

**Comment by twpayne** [comment]
For info, what I think happened here is that I made a change to a file that was read by a non-Go process spawned with a testscript `exec` and consequently the access was not caught by `os.Open`/`testlog`. The error was in the test I wrote - it should not have accessed a file outside `$WORK`. Once I fixed the test, the problem no longer existed.

**Comment by matthewmueller** [comment]
Slightly related, but adding to this in case anyone else runs into trouble. 

If you're testing library code from within a test script, it may be cached despite that application code changing because there's no clear link between the test script and the library code.

To fix this, you can force a link within your tests, something like:

```go
func Test(t *testing.T) {
	// This is here to make sure the cache is invalidated by changes to the CLI
	cli.Run()
	p := testscript.Params{
		Cmds: map[string]func(ts *testscript.TestScript, neg bool, args []string){},
		Setup: func(e *testscript.Env) error {
			e.Vars = append(e.Vars,
				"GONOSUMDB=*",
			)
			return nil
		},
	}
	if err := gotooltest.Setup(&p); err != nil {
		t.Fatal(err)
	}
	testscript.Run(t, p)
}
```
