### ISSUE TITLE
testscript: add chezmoi to users of testscript Wiki page

### ISSUE THREAD

**Issue by twpayne** [rogpeppe/go-internal#101]
Random folk can't edit the [Users of testscript wiki page](https://github.com/rogpeppe/go-internal/wiki/Users-of-testscript) so please can you add:

[`github.com/twpayne/chezmoi`](https://github.com/twpayne/chezmoi): [bootstrap](https://github.com/twpayne/chezmoi/blob/master/main_test.go) • [scripts](https://github.com/twpayne/chezmoi/tree/master/testdata/scripts)

Thanks so much to @myitcv for [sharing testscript on golang-nuts](https://groups.google.com/d/msg/golang-nuts/98SJJorDzhI/Crw_4NQkCwAJ) in January. testscript fits my needs perfectly, and is a very well thought-through system :)

**Comment by myitcv** [comment]
Done. Glad you're enjoying testscript!
