### ISSUE TITLE
Release a new version > 0.0.8 post import path change

### ISSUE THREAD

**Issue by rrrkren** [rogpeppe/go-internal#14]
When I run ```go get github.com/rogpeppe/go-internal``` in a go module, I get pinned to v0.0.8, which was probably released before you guys changed the repository name to go-internal. Thus breaks and complains:
```
go: github.com/rogpeppe/go-internal@v0.0.8: parsing go.mod: unexpected module path "github.com/rogpeppe/modinternal"
go: error loading module requirements
``` 
when I pin it to v1.0.0alpha the problem goes away, is there a better solution than this? how stable is this alpha version?

**Comment by rrrkren** [comment]
it seems the only difference between 0.0.8 and 1.0.0-alpha is the name change.

**Comment by myitcv** [comment]
Yes, I pinged @rogpeppe to do a proper release to fix this. Hopefully soon 😄

**Comment by myitcv** [comment]
Re-opening and retitling to be the action "Release a new version > 0.0.8 post import path change"

**Comment by myitcv** [comment]
Fixed via https://github.com/rogpeppe/go-internal/releases/tag/v1.0.0
