### ISSUE TITLE
Need new export of testscript

### ISSUE THREAD

**Issue by zellyn** [rogpeppe/go-internal#143]
go1.16 added `SetPanicOnExit0` to the `testing.testDeps` interface ([docs](https://pkg.go.dev/testing/internal/testdeps#TestDeps.SetPanicOnExit0))

Trying to use this package with go 1.16 gives:

`nopTestDeps does not implement testing.testDeps (missing SetPanicOnExit0 method)`

**Comment by mvdan** [comment]
You might be on an older testscript; we've had this for a year :) https://github.com/rogpeppe/go-internal/commit/1115b6af0369aff6bd0766818c61a9a75678c6cc

**Comment by zellyn** [comment]
Oh weird! I guess `go get` pulled down a weird version :-)

Thanks, and sorry for the noise!
