### ISSUE TITLE
Port 'cmd/go: add mv and support "! cmp" in script tests'

### ISSUE THREAD

**Issue by myitcv** [rogpeppe/go-internal#153]
From https://go-review.googlesource.com/c/go/+/380916

**Comment by mvdan** [comment]
I'll take a stab at this as I want `! cmp` for https://github.com/burrowers/garble.

**Comment by bitfield** [comment]
Just one comment, and I realise this applies to upstream too: it's a little confusing that you can't `mv` files into a directory the same way you can with `cp`:

```txt
mkdir new

# works
cp a.txt b.txt new

# doesn't work
mv a.txt b.txt new

-- a.txt --
-- b.txt -- 
```

**Comment by myitcv** [comment]
Hmm I'd say that probably warrants a new issue to capture that. Feels like an oversight in the upstream implementation?
