### ISSUE TITLE
testscript: errors returned in testscript.Params.Setup aren't shown to the user

### ISSUE THREAD

**Issue by mvdan** [rogpeppe/go-internal#17]
In some tests of mine, I was seeing:

```
$ go test
--- FAIL: TestGenerateError (0.00s)
    --- FAIL: TestGenerateError/empty (0.00s)
    --- FAIL: TestGenerateError/eval (0.00s)
    --- FAIL: TestGenerateError/fmt (0.00s)
    --- FAIL: TestGenerateError/cmds (0.00s)
```

`go test -v` didn't help either. It's only after adding a `fmt.Println(err)` in the setup func that I was able to see the error.

Sounds like we just forgot to surface these errors to the user somewhere.

**Comment by bitfield** [comment]
I can't reproduce this now, @mvdan, can you?

Adding an error return to a `Setup` func causes every script to fail and print the error:

```
--- FAIL: TestScripts (0.00s)
    --- FAIL: TestScripts/nothing (0.00s)
        testscript.go:429: FAIL: testdata/nothing.txtar:0: oh no
            
    --- FAIL: TestScripts/regexpquote (0.00s)
        testscript.go:429: FAIL: testdata/regexpquote.txt:0: oh no
            
    --- FAIL: TestScripts/setenv (0.00s)
        testscript.go:429: FAIL: testdata/setenv.txt:0: oh no
...
```

Or am I misunderstanding what you meant?

**Comment by mvdan** [comment]
This error is so old that you're probably right :) I haven't encountered the problem since, either.
