### ISSUE TITLE
testscript: $WORK does not appear to be filled correctly

### ISSUE THREAD

**Issue by verdverm** [rogpeppe/go-internal#182]
```
exec bash -c 'env'
exec cat $WORK/data.cue
cmp stdout data.cue
exec bash -c 'cat $WORK/data.cue'
cmp stdout data.cue

-- data.cue --
a: "a"
b: 2

val: foo: "bar"
```

running this has the following output, bash version is similar

```
$ testscript adhoc-absolute.txt 
> exec bash -c 'env'
[stdout]
:=:
/=/
$=$
PWD=$WORK
GOARCH=amd64
HOME=/no-home
TMPDIR=$WORK/.tmp
TESTSCRIPT_COVER_DIR=
GOROOT=/usr/local/go
WORK=$WORK
exe=
goversion=1.19
GOPROXY=https://proxy.golang.org,direct
SHLVL=0
GOCACHE=/home/tony/.cache/go-build
CCACHE_DISABLE=1
devnull=/dev/null
PATH=/home/tony/.local/bin:/home/tony/.config/nvm/versions/node/v17.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sonar-cloud/bin:/home/tony/bin:/usr/local/go/bin:/home/tony/go/bin:/home/tony/.npm-global/bin:
GOOS=linux
GOPATH=$WORK/.gopath
_=/usr/bin/env
> exec cat $WORK/data.cue
[stdout]
a: "a"
b: 2

val: foo: "bar"

> cmp cat expected.txt
FAIL: /tmp/testscript915784671/adhoc-absolute.txt/script.txtar:3: open $WORK/cat: no such file or directory
error running adhoc-absolute.txt in /tmp/testscript915784671/adhoc-absolute.txt
```

**Comment by mvdan** [comment]
I'm confused. Where is `expected.txt` coming from in your output? I just ran your script above via `cmd/testscript` and I didn't get a failure either.

**Comment by verdverm** [comment]
I think there were two things going on here (pebkac)
- outdated `testscript`
- copying the wrong ts output

**Comment by verdverm** [comment]
It doesn't always seem to have expected output though...

```
exec echo $WORK
exec bash -c 'echo $WORK'
exec cat $WORK/data.cue
cmp stdout data.cue

-- data.cue --
a: "a"
b: 2

val: foo: "bar"
```

testscript -v repro.txt

```
$ ts -v repro.txt 
WORK=$WORK
PATH=/home/tony/.bun/bin:/home/tony/.local/bin:/home/tony/.config/nvm/versions/node/v17.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sonar-cloud/bin:/home/tony/bin:/usr/local/go/bin:/home/tony/go/bin:/home/tony/.npm-global/bin:
HOME=/no-home
TMPDIR=$WORK/.tmp
devnull=/dev/null
/=/
:=:
$=$
TESTSCRIPT_COVER_DIR=
exe=
GOPATH=$WORK/.gopath
CCACHE_DISABLE=1
GOARCH=amd64
GOOS=linux
GOROOT=/usr/local/go
GOCACHE=/home/tony/.cache/go-build
GOPROXY=https://proxy.golang.org,direct
goversion=1.19

> exec echo $WORK
[stdout]
$WORK
> exec bash -c 'echo $WORK'
[stdout]
$WORK
> exec cat $WORK/data.cue
[stdout]
a: "a"
b: 2

val: foo: "bar"
> cmp stdout data.cue
PASS
```

any idea why it's working in some places and not others? There seem to be situations where it is not substituted before sending to exec or not available for substitution

**Comment by bitfield** [comment]
Could it be that you're running into this:

> Note also that in reported output, the actual name of the per-script temporary directory has been consistently replaced with the literal string `$WORK`.
—https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript

In other words, if you try to `exec echo $WORK` in your script, it will print the real path to the script's workdir, but you don't _see_ that in the output, because the real path to the workdir is always replaced by the literal string `$WORK`—even if it's generated some other way. This surprised me a bit too, but the rationale (reproducibility) makes sense.

**Comment by verdverm** [comment]
seems so, after fixing the bug in my code, the test passes as is

**Comment by bitfield** [comment]
This is what I say about it in [The Power of Go: Tests](https://bitfieldconsulting.com/books/tests) [`plug MODE=shameless`]

> If scripts need to know the absolute path of their work directory, it will be available as `$WORK`. For example, we could use `$WORK` as part of the value for another environment variable:

```txtar
env CACHE_DIR=$WORK/.cache
```

> To make scripts deterministic, though, the actual *value* of this variable will be replaced in the `testscript` output by the literal string `$WORK`. In fact, the value of `$WORK` will be different for every run and every test, but it will always *print* as simply `$WORK`.

Would a little explanatory note along these lines make a useful addition to the docs?

**Comment by verdverm** [comment]
Probably, is there an official location for the docs?

**Comment by bitfield** [comment]
https://github.com/rogpeppe/go-internal/blob/7a6a5f804c24039a8741921b97ffa0c3b8998be3/testscript/doc.go would likely be the place for this, I think.
