### ISSUE TITLE
testscript: signal or some other way to interrupt running command

### ISSUE THREAD

**Issue by ldemailly** [rogpeppe/go-internal#195]
I want to be able to test ^C behavior and long running but interruptible programs and not having a pid from `&` I don't know how to do it

otherwise testscript is near perfect!

```
# how to do this
dnsping www.google.com 8.8.8.8 &
exec sleep 3
exec kill %1 # this doesn't exist/work - doesn't reference the dnsping sub process above
wait
stderr 'will query until interrupted'
stdout '0 errors \(0.00%\), [34] success.'
```

right now I found this workaround but it's brittle (relies on the exec being called same as the go command and nothing else being called same - and also doesn't work on ci)

```
exec pkill -x dnsping # todo want something like kill %1 instead
```

https://github.com/fortio/dnsping/pull/17/files#diff-c93182c79a5fb9ceb9b9ba653ab9acd3ea10510a75167c5972e3890fa799389bR76

**Comment by ldemailly** [comment]
Am I not seeing a way to achieve that? (got reminded of this reading #228 where setup go side is mentioned but I am also looking for something in txtar)

**Comment by mvdan** [comment]
Let's consolidate under https://github.com/rogpeppe/go-internal/issues/242, since that issue has an open PR.
