### ISSUE TITLE
testscript: "signal: killed" exec errors on MacOS 12

### ISSUE THREAD

**Issue by mvdan** [rogpeppe/go-internal#200]
```
     --- FAIL: TestScript/flags (0.11s)
        testscript.go:429: > exec shfmt -h
            [signal: killed]
            FAIL: testdata/script/flags.txtar:1: unexpected command failure
```

I've seen this in a number of projects of mine, like:

* https://github.com/burrowers/garble/pull/614
* https://github.com/mvdan/sh/pull/934#issuecomment-1287113938
* https://github.com/mvdan/sh/commit/461be7eb20ff0eca28755287f192b258f0ac3a34

@rvagg mentions the same crash in https://github.com/ipld/go-car/pull/364, and in the past, others like @mr-joshcrane have mentioned the same error on Slack.

This must be something going wrong with either testscript or Go, because for example, that `TestScript/flags` test from above was just running `exec shfmt -h`, showing the help output from a Go program. You can see that the testscript file is [rather boring](https://github.com/mvdan/sh/blob/6bbe558780e0a77d24ab452c0f182ac25ecc16cc/cmd/shfmt/testdata/script/flags.txtar), so it's not doing anything particularly worrying.

Personally, I've worked around this by downgrading from `macos-latest` on GitHub Actions (which switched to `macos-12` late last year) to `macos-11`, which seems to make the failures go away entirely. But of course that's not a complete fix.

I first hoped that this would be fixed in Go 1.20 with https://go-review.googlesource.com/c/go/+/460476, and that may still be true, given that there are four distinct os/exec bugs for Mac there. But it's just a good guess, I haven't verified this yet - nor do I have a Mac machine to test with. Help would be appreciated.

The only other recent mentions of "signal: killed" upstream for Mac are https://github.com/golang/go/issues/57418 and https://github.com/golang/go/issues/57239, and they both seem to point to processes being OOM-killed by the system. This could be the case for us as well, perhaps either due to the OS version upgrade changing the OOM behavior, or perhaps because the `macos-12` GitHub machines have less available memory. But I'd also find it hard to believe, given that testscript doesn't use a particularly high amount of memory.

Filing this issue to track investigation and progress.

**Comment by bitfield** [comment]
Just as a data point, I've never managed to reproduce this on macOS 10, despite many attempts.

**Comment by mvdan** [comment]
I've never seen this error on macos-10 nor macos-11 on GitHub Actions despite having used testscript for years, only on its macos-12, so I'm pretty sure that this bug only happens on MacOS 12.

**Comment by ldemailly** [comment]
I see this as well

**Comment by bep** [comment]
I see this as well, but on Ubuntu (ubuntu-latest) with Go 1.20. I needed to remove Go 1.20 from the build matrix of one project ... I will investigate later.

https://github.com/gohugoio/hugoreleaser/issues/38

**Comment by mvdan** [comment]
@bep perhaps I'm missing something, but I can't find a single mention of either "signal" or "killed" in those logs. The failures seem pretty normal - some commands inside your testscripts are failing when the script expects them to succeed.

**Comment by mvdan** [comment]
"unexpected command failure" is one of the relatively normal error messages you will get with testscript when the tests fail. This particular bug only happens on MacOS 12, and noone has been able to reproduce it on Linux that I am aware of, so it seems very unlikely that you're running into the same bug.

**Comment by bep** [comment]
>"unexpected command failure" is one of the relatively normal error messages you will get with testscript when the tests fail.

As I said, I'm pretty sure these `unexpected command failure` are ... unexpected and that they come from flakiness in the test infrastructure that's become more flaky in Go 1.20. But you're right, It's probably a _different_ flakines issue; I will create a different issue somewhere once I figure out a little better who to blaim.

**Comment by mvdan** [comment]
@rogpeppe has been seeing the same failures now on `macos-11`, in PRs to this very repo. In particular, the OS version appears to be 11.7.4, and the failures happen on both Go 1.19.x and 1.20.x.

Perhaps whatever changed in macos-12 to trigger this bug was backported to macos-11 now.

**Comment by ldemailly** [comment]
I guess (possibly wrong) it's a background version of what happens when you run a new binary:

<img width="407" alt="Screen Shot 2023-03-30 at 2 46 42 PM" src="https://user-images.githubusercontent.com/3664595/228971806-2f51d37c-c73f-4c37-a320-1335eb1de5c5.png">

followed by "Killed: 9" when clicking ok

**Comment by bitfield** [comment]
@ldemailly, that sounds like a reasonable idea, but if that's the case, how come it doesn't happen every time, and how come it doesn't happen when you run `go test`? I mean, that is building and executing a binary in the background. All `testscript` does is re-exec the same binary, so I can't work out why `testscript` commands appear to fail frequently (but apparently randomly) on all modern macOS versions, while `go test` never does.

**Comment by bep** [comment]
This has become a real issue for me, so I decided to take a look at it, and I found that there's a correlation between the size/amount of commands added to `RunMain` and this issue. I added a patch in the PR below that fixes this on my MacBook, a sleep after the commands gets written to disk (which I assume allow the OS to flush) and before the test execution. 

See https://github.com/rogpeppe/go-internal/pull/219

**Comment by myitcv** [comment]
Drive-by noting another alternative here to hard linking on macOS: copy on write. That probably requires detection of some sort and a specific system call) but it will be more efficient than a full copy (because there will be no write).

**Comment by mvdan** [comment]
Thanks, @myitcv. @bep reports that symlinks don't have the problem on MacOS that hard links do, which sort of makes sense: we are not creating new executable files, just symbolic links. Unless anyone disagrees, I think giving symlinks a go is worthwhile. We can then see if they cause any unforeseen issues on either Linux or Mac - I hope not. They should also be slightly more versatile than hard links, as hard links generally require both ends to be on the same filesystem.

**Comment by mvdan** [comment]
Hit enter too soon :) If the symlink approach fails, then I agree that we could try `clonefile` before falling back to something like full copies.

**Comment by mvdan** [comment]
@myitcv correctly points out that I wrote this bit of text in the `copyBinary` godoc, which does explain why I originally tried symlinks and moved away from them:

```
// It does not attempt to use symlinks for two reasons:
//
// First, some tools like cmd/go's -toolexec will be clever enough to realise
// when they're given a symlink, and they will use the symlink target for
// executing the program. This breaks testscript, as we depend on os.Args[0] to
// know what command to run.
//
// Second, symlinks might not be available on some environments, so we have to
// implement a "full copy" fallback anyway.
```

Also worth noting that https://pkg.go.dev/os#Executable says:

> If a symlink was used to start the process, depending on the operating system, the result might be the symlink or the path it pointed to. If a stable result is needed, path/filepath.EvalSymlinks might help.

The API makes no guarantees, but if any code currently makes assumptions about the executable being a regular file, that might be silently broken with the change to symlinks.

I'll take another look at my usecase with `go build -toolexec` to see if it still gets confused by symlinks.

As for the API that Paul suggests, it's at https://pkg.go.dev/golang.org/x/sys/unix?GOOS=darwin#Clonefile. @bep does that reproduce the bug? Presumably it doesn't result in higher disk usage. https://eclecticlight.co/2023/04/28/apfs-hard-links-symlinks-aliases-and-clone-files-a-summary/ explains how the system treats hard links and clone files differently. Given that the Finder UI uses clone files and _not_ hard links by default when making copies of files within the same filesystem, it sounds to me like clone files might behave better with executables.

**Comment by myitcv** [comment]
> As for the API that Paul suggests, it's at https://pkg.go.dev/golang.org/x/sys/unix?GOOS=darwin#Clonefile.

Just to check (because I'm naive in these things), is this definitely the syscall for `clone2`?

**Comment by mvdan** [comment]
It's `clonefile`, the one you linked to above: https://cs.opensource.google/go/x/sys/+/refs/tags/v0.8.0:unix/zsyscall_darwin_amd64.go;l=1011

Where do you see `clone2`? I only see `clonefile(2)`, but that is just the rather confusing man page syntax to say that `clonefile` is in the category `2   System calls (functions provided by the kernel)`, per `man man`.

**Comment by mvdan** [comment]
Full copy on Windows, Clonefile on Mac, and hard links on Linux sound good to me. Beware that we likely need build tags now, since `unix.Clonefile` is only defined for `GOOS=darwin`. Perhaps we can add a `cloneFile` func which is `os.Link` on `unix && !darwin`, `unix.CloneFile` on `darwin`, and `return fmt.Errorf("unavailable")` on `!unix`.

`testscript.Params.Cmds` don't run as separate programs and processes via `os/exec`, instead running in-process via a function call. That makes them a lot cheaper indeed. Less powerful as well, but for small test helpers and utilities, I find them pretty useful. In medium-to-large projects, I often end up with 1-3 `TestMain` commands, often to run the "real" main program in different modes, and 5-15 `testscript.Params` commands.

**Comment by bep** [comment]
>Full copy on Windows, Clonefile on Mac, and hard links on Linux sound good to me. Beware that we likely need build tags now, since unix.Clonefile is only defined for GOOS=darwin. Perhaps we can add a cloneFile func which is os.Link on unix && !darwin, unix.CloneFile on darwin, and return fmt.Errorf("unavailable") on !unix.

I can prepare a PR with something ala the above in a few hours.

**Comment by myitcv** [comment]
@bep - thanks very much for digging in here to get this fixed.

**Comment by ldemailly** [comment]
it's fantastic to have a solution, I'm just a bit confused as to why symlink isn't even better/simpler?

**Comment by mvdan** [comment]
@ldemailly see the previous comments, particularly https://github.com/rogpeppe/go-internal/issues/200#issuecomment-1536127648.

**Comment by ldemailly** [comment]
oic "[tools like go] will use the symlink target"

that seems like a bug though if they cause the args0 to change as it's fairly common to rely on that (also that mr did pass all tests so presumably it's actually working ?)

what's the size of the directory when using clonefile?

**Comment by ldemailly** [comment]
oic, neat, from the man page:

     The cloned file dst shares its data blocks with the src file [...]
     
     Subsequent writes to either the original or cloned file are private to
     the file being modified (copy-on-write).

except for EXDEV possible issue (are we sure we stay on same FS?)

**Comment by mvdan** [comment]
There is no guarantee that the source and destination are the same filesystem. Which is why there is a fallback with regular file copying.

**Comment by ldemailly** [comment]
Thanks for the explanation (that there is a fallback already).

So a symlink, in theory, if not for that (possibly outdated?) `go build -toolexec` issue would be always working (and smallest disk use).

Either way I think the current solution is great and matches the previous hardlink behavior (fs wise), so it's awesome and indeed I don't see "killed" anymore on my mac 🎉
