### ISSUE TITLE
Command go allowed in some txtar scripts and not in others, please document

### ISSUE THREAD

**Issue by rudifa** [rogpeppe/go-internal#234]
I was intrigued by the difference between `.txtar` files intended for running with `testscript first.txtar` and those intended for running with `go test other.txtar`.

The files ran by `testscript` support the command `go` with a variety of arguments, as documented in `testscript -h`, in addition to commands, conditions and supporting files that are interpreted by the `small script engine in the testscript package`; files run by `go test` do not support the command `go`.

I suggest that this difference should be mentioned and documented in [testscript doc](https://pkg.go.dev/github.com/rogpeppe/go-internal@v1.11.0/testscript), for the benefit of newcomers.

**Comment by mvdan** [comment]
The difference is https://pkg.go.dev/github.com/rogpeppe/go-internal/gotooltest. It's true that the gotooltest package is not linked from the testscript package's documentation, so I'd happily approve a small patch doing that.

**Comment by mvdan** [comment]
Your PR above clarified this.
