### ISSUE TITLE
Release for the latest tag

### ISSUE THREAD

**Issue by sieuwerts** [rogpeppe/go-internal#254]
Could we perhaps do an official release for the latest v1.12.0 tag? `go get -u` does not recognise this as an updated version but [renovate](https://github.com/renovatebot/renovate) does. Since the tag exists, it would be nice to have a release related to it.

Thanks!

**Comment by mvdan** [comment]
Sure, done for consistency with earlier releases. But `go get` should not care about GitHub releases at all; it is based purely on git tags. I think you are having some other unrelated issue.
