### ISSUE TITLE
question: flakyness meaning in robustio

### ISSUE THREAD

**Issue by elv-gilles** [rogpeppe/go-internal#264]
Looking at package `robustio`, darwin is deemed flaky and Rename, RemoveAll and ReadFile are retried up to some `arbitraryTimeout`  while linux is not deemed flaky.

During discussion around an issue we have in our system, I got the following observation:
>The OS is not really the problem - it's the file system. On both linux and darwin one can use different file systems and each will have its own consistency semantics. So I think making any decisions based on OS is not a good idea.

Would you please share any thought around that ?

**Comment by mvdan** [comment]
The code, godocs, and comments are largely borrowed from the Go codebase - they support the main OSes on a best-effort basis. https://pkg.go.dev/cmd/go/internal/robustio

**Comment by mvdan** [comment]
Closing as resolved, because we haven't made these (hard) choices ourselves.
