### ISSUE TITLE
Question: Is it possible to store `stdout` for later in `testscript`?

### ISSUE THREAD

**Issue by williammartin** [rogpeppe/go-internal#274]
## Question

I'm exploring a test script that looks like:

```
# Use gh as a credential helper
exec gh auth setup-git

# Create a repository with a file so it has a default branch
exec gh repo create $ORG/$SCRIPT_NAME-$RANDOM_STRING --add-readme --private

# Defer repo cleanup
defer gh repo delete --yes $ORG/$SCRIPT_NAME-$RANDOM_STRING

# Clone the repo
exec gh repo clone $ORG/$SCRIPT_NAME-$RANDOM_STRING

# Prepare a branch to PR
cd $SCRIPT_NAME-$RANDOM_STRING
exec git checkout -b feature-branch
exec git commit --allow-empty -m 'Empty Commit'
exec git push -u origin feature-branch

# Create the PR
exec gh pr create --title 'Feature Title' --body 'Feature Body'

# View the PR
exec gh pr view 1
stdout 'Feature Title'
```

You can see in the final section I hard code a `1`, indicating the Pull Request created has number `1`. However, a more robust way to approach this in case of future parallelism would be to store the stdout of the previous command (which outputs the URL of the newly created PR).

I know that there is a `stdin stdout` incantation but this doesn't quite work when:
 * We're not working with `stdin`
 * The commands are separated by intermediary commands (another case I have)

I had a look at the implementation for `env` but it doesn't seem to provide the same capability as `stdin`.

Perhaps the best thing for me to do is write a custom command but I guess I need to explore what is available in there. Am I missing something? Thanks!

**Comment by mvdan** [comment]
you can `cp stdout some-file-path`, if that's what you mean.

**Comment by williammartin** [comment]
Thanks for the quick response. It's not quite what I meant but maybe I can use it to achieve the same thing?

Is there an inbuilt mechanism for getting the contents of a file into something that can be passed as an argument to a command?

**Comment by mvdan** [comment]
Not out of the box, but doing a "read file into env var" command is trivial: https://github.com/burrowers/garble/blob/48dd2263a90b67a2d3997f5b3b1b7cf537a35ea1/main_test.go#L142

**Comment by williammartin** [comment]
Heh, yeh that's pretty much what I ended up writing as `stdout2env` just now. Thanks very much for your help!

**Comment by williammartin** [comment]
Totally understand. Mainly I just wondered if I was missing an obvious solution and I hadn't initially clocked that `ts.ReadFile` handled the stdio cases.
