### ISSUE TITLE
## Description

### ISSUE THREAD

**Issue by Nopathway** [rogpeppe/go-internal#279]
## Description

By default, `testscript` runs every script in a dir in parallel, which is a great choice. Unfortunately, in my use case of testing the `gh` command, the GitHub API has pretty aggressive rate limiting for concurrent requests and just a few scripts creating resources in parallel is exceeding the limit.

My choices right now seem to be:
 * Create a setup mechanism for resources in Go so that scripts can share resources.
 * Invoke `testscript.Run` for each individual file so that the subtests created by `testscript` don't have the same parent and aren't parallelised

I'm very keen to avoid the first choice because it reduces the script readability, increases maintenance burden with shared code paths, and reduces test isolation due to shared resource usage.

The second one seems acceptable but feels a bit heavyweight for what amounts to a conditional that `testscript` could handle.

Would you be open to a new testscript param `Sequential` that is used to conditionally wrap the call to `t.Parallel()`?

---

I understand that my usage of `testscript` here is probably a bit non-idiomatic and a more comprehensive answer is "have a better test infrastructure". I certainly won't take it personally if you don't want to accept something like this, but as a maintainer of `gh` project I find it useful when people share their use cases and sharp edges. I hope you do as well, rather than just finding me a pest 😅 

Cheers!

_Originally posted by @williammartin in https://github.com/rogpeppe/go-internal/issues/277_

**Comment by mvdan** [comment]
Stop spamming this repository, thanks.
