### ISSUE TITLE
Please include a copy of src/cmd/go/internal/modcmd to get the official info file structures

### ISSUE THREAD

**Issue by nim-nim** [rogpeppe/go-internal#65]
This project really helps trying to do things with go modules but it is incomplete as it stands.

It is missing src/cmd/go/internal/modcmd that defines the official structure of a go module info file.

**Comment by nim-nim** [comment]
And the tidy functions in the same package would also be real useful

**Comment by myitcv** [comment]
Thanks - can you give a bit more background on what it is you're trying to do here, and exactly which part of the package API you'd therefore use? Thanks

**Comment by nim-nim** [comment]
I need the bit that defines the content of an info file structure

https://tip.golang.org/cmd/go/#hdr-Module_proxy_protocol states
> The JSON-formatted metadata about a given module corresponds to this Go data structure, which may be expanded in the future

This is not terribly helpful, that means "things will break" in the future, having an official definition of the struct would prevent discovering things are broken when they are broken in production.

I thought I had found the definition in `src/cmd/go/internal/modcmd` but I'm not finding it anymore (arguably, info is such a generic search term, it's hard to locate).

The second need is to have a way to ask go to re-tidy the .mod file corresponding to a specific zip (I should really have opened a separate ticket about this, I can if you want)

This probably involves calling things in `src/cmd/go/internal/modcmd/tidy.go` but I've not progressed far enough to identify exactly which parts are needed

**Comment by nim-nim** [comment]
> I thought I had found the definition in `src/cmd/go/internal/modcmd` but I'm not finding it anymore 

It's probably intended to be a subset of RevInfo  in
https://github.com/golang/go/blob/master/src/cmd/go/internal/modfetch/codehost/codehost.go

Don't really see where the subset is defined

**Comment by mvdan** [comment]
Thanks for opening this issue and apologies that it's already been four years without much of a conclusive reply.

Forking each upstream packags is a significant amount of work - not only the initial copying, but stabilizing the APIs and porting updates over the years. We are already struggling to keep up with the existing number of packages, and particularly with testscript given its popularity, so I don't think we should add more packages that implement cmd/go's support for modules. You are of course welcome to copy those packages yourself for your projects, but for now, we don't have the time to do it ourselves.
