### ISSUE TITLE
Please include a copy of /src/cmd/go/internal/modfetch to manipulate module list files

### ISSUE THREAD

**Issue by nim-nim** [rogpeppe/go-internal#66]
Please include a copy of /src/cmd/go/internal/modfetch, the only thing that specifies what a module list file is and how it should be generated is rewriteVersionList

**Comment by myitcv** [comment]
Thanks - can you give a bit more background on what it is you're trying to do here, and exactly which part of the package API you'd therefore use? Thanks

**Comment by nim-nim** [comment]
I'm trying to generate module files from expanded go source archives, with a little more control of what ends up in the module files, than the go tooling currently does.

Current go module tooling will just blindly zip everything located bellow a go.mod. This is nicely agnostic, but it does not help you to check if what's bellow the go.mod is really what you want to end up in the module (I've seen modules that contained .gitignores for example; this is completely harmless, but it highlights how blind the module generator is).

Once you've written the code to filter and sanity check files, and put them in a zip, write the info & hash file (all of which can be done with the internal code you already mirror) you need to generate lists files for go to accept the result as a valid goproxy.

As far a I can see, list files are woefully under specified, and are whatever rewriteVersionList outputs in modfetch

**Comment by nim-nim** [comment]
Basically, I would need something to write info files from RevInfo? and something else to parse (simplified?) RevInfos from module.Version

**Comment by mvdan** [comment]
Thanks for opening this issue and apologies that it's already been four years without much of a conclusive reply.

Forking each upstream packags is a significant amount of work - not only the initial copying, but stabilizing the APIs and porting updates over the years. We are already struggling to keep up with the existing number of packages, and particularly with testscript given its popularity, so I don't think we should add more packages that implement cmd/go's support for modules. You are of course welcome to copy those packages yourself for your projects, but for now, we don't have the time to do it ourselves.
