### ISSUE TITLE
Please include a copy of /src/cmd/go/internal/modfetch to get the functions necessary to parse Go module pseudoversions

### ISSUE THREAD

**Issue by nim-nim** [rogpeppe/go-internal#67]
The pseudoversion parsing code is in  [cmd/go/internal/modfetch](https://godoc.org/cmd/go/internal/modfetch) as documented in https://github.com/golang/go/issues/31077

**Comment by mvdan** [comment]
Thanks for opening this issue and apologies that it's already been four years without much of a conclusive reply.

Forking each upstream packags is a significant amount of work - not only the initial copying, but stabilizing the APIs and porting updates over the years. We are already struggling to keep up with the existing number of packages, and particularly with testscript given its popularity, so I don't think we should add more packages that implement cmd/go's support for modules. You are of course welcome to copy those packages yourself for your projects, but for now, we don't have the time to do it ourselves.
