### ISSUE TITLE
testscript: background cmds break -coverprofile

### ISSUE THREAD

**Issue by mvdan** [rogpeppe/go-internal#73]
testscript tries to merge coverage profiles, but this is broken with background commands. It seems like the reason is that testscript expects the background cmd to write its coverage file immediately, not at the end of the test once it's interrupted.

**Comment by vishen** [comment]
I am running into this issue at the moment as well: `go test ./... -coverprofile=cov.out` is causing `command <cmd> failed to generate coverage information` . Is this something that could be changed, or is unlikely to change?

**Comment by mvdan** [comment]
I'm pretty sure this could be changed, it just requires someone to refactor the code a bit to allow adding coverage info when background processes are cleaned up. Perhaps @rogpeppe has thoughts, since he wrote a lot of this code coverage merging logic.

**Comment by mvdan** [comment]
We no longer need to collect and merge coverage files ourselves (https://github.com/rogpeppe/go-internal/pull/201) so I believe this is no longer an issue :)
