### ISSUE TITLE
testscript: flag -testwork doesn't keep files

### ISSUE THREAD

**Issue by leitzler** [rogpeppe/go-internal#78]
Log files are written to `/tmp/go-test-scriptNNNNNNNNNN` by the testscript framework.

When using the flag `-testwork` in the origin, those files are preserved:
https://github.com/golang/go/blob/25a2b98f7a1454aac0d7d3072f74613ac0446630/src/cmd/go/script_test.go#L53-L55

While the persistence decision has been moved to testscript parameters here:
https://github.com/rogpeppe/go-internal/blob/master/testscript/testscript.go#L169-L177

Shouldn't the flag be considered as well?

**Comment by myitcv** [comment]
cc @rogpeppe

**Comment by rogpeppe** [comment]
see comment in the linked issue
