### ISSUE TITLE
testscript: interest in syntax highlighting?

### ISSUE THREAD

**Issue by twpayne** [rogpeppe/go-internal#97]
Is there any interest in syntax highlighting for `testscript` scripts?

I'm about to write a lot of `testscript` scripts and having some syntax highlighting will definitely speed up my development. However, it's also a non-trivial chunk of work, so I'd like to gauge interest before starting.

My primary development environment is VSCode, but I've also used VIM a lot in the past, so would also consider writing a VIM plugin.

**Comment by rogpeppe** [comment]
Personally I don't use an editor that has syntax highlighting, so I can't speak on this, but others might have an opinion. @mvdan @myitcv 

The syntax is pretty simple, so I suspect that it shouldn't be _that_ much work.

**Comment by myitcv** [comment]
I have the following setup locally using https://github.com/inkarkat/vim-SyntaxRange:

<img width="841" alt="Screen Shot 2020-05-06 at 11 57 04" src="https://user-images.githubusercontent.com/3374574/81169541-e8156400-8f90-11ea-89e9-f99083c6a9be.png">

* `bash` highlighting for the "top section" of the txtar
* highlighting of the file boundaries within the txtar archive
* language highlighting based on the file type of the file in txtar archive

I'll try and distill this out at some point.

**Comment by mvdan** [comment]
I don't personally use syntax highlighting, but it would still be nice for a quick how-to to get vim to see the different syntax sections of a txtar file. It can be useful to be able to properly indent Go files inside a txtar file, even if no syntax highlighting is used.

**Comment by twpayne** [comment]
Thanks for the feedback all. I decided to go ahead and implement a basic VIM syntax highlighting plugin. It's not perfect, but it's a reasonable start, and includes a few nice features like highlighting predefined variables and conditions specially. `${:}` and `${/}` are highlighted as delimiters.

<img width="743" alt="vim-testscript" src="https://user-images.githubusercontent.com/6942/81240137-78d65900-8ffe-11ea-846b-d9698799bc76.png">

The code is at https://github.com/twpayne/vim-testscript. Contributions welcome, and I propose to integrate @myitcv's solution when he shares it.

**Comment by myitcv** [comment]
Ok, now that a fix has been merged for https://github.com/inkarkat/vim-SyntaxRange it makes sense to share my setup. 

```vim
function s:Highlight(...)
  hi Mine ctermfg=236 ctermbg=150 guifg=#303030 guibg=#afd787
  call SyntaxRange#IncludeEx('start="\%^" end="^\ze-- .* --$" containedin=ALL keepend', 'bash')
  let files = [
        \ [["markdown", "md"], "markdown"],
        \ [["cue"], "cue"],
        \ [["go"], "go"],
        \ [["mod"], "gomod"],
        \ [["sh", "bash"], "bash"],
        \]
  for f in files
    call SyntaxRange#IncludeEx('matchgroup=Mine start="^-- .*\.\('.join(f[0],'\|').'\)\(\.golden\)\? --$" end="^\ze-- .* --$" containedin=ALL keepend', f[1])
  endfor
  syn match Mine '^-- .* --$' containedin=ALL
  setlocal commentstring=#%s
endfunction

autocmd BufNewFile,BufRead *.txt call s:Highlight()
```

Obviously you can add to/remove from that filetype list as you wish. Just as you can define your own highlight group for the txtar file headers.

As you can see from the regular expressions, syntax highlighting for the section is determined by the file extension. `.golden` is allowed as a special suffix for the cases where golden files are required.

**Comment by twpayne** [comment]
I had another look at this and implemented a VSCode extension for syntax highlighting testscripts, including highlighting embedded files.

Grab it from https://marketplace.visualstudio.com/items?itemName=twpayne.vscode-testscript. Feedback welcome.

<img width="388" alt="example" src="https://user-images.githubusercontent.com/6942/144708946-2d55765c-6587-4226-97fc-85780e3adcf0.png">

**Comment by twpayne** [comment]
With the above, my personal needs for syntax highlighting of testscripts are met, so closing this issue.

**Comment by twpayne** [comment]
An improved plugin for VSCode: https://github.com/brody715/vscode-txtar

This independently includes suggestions that @myitcv suggested.

I opened https://github.com/brody715/vscode-txtar/issues/1 to discuss which plugin to use.

**Comment by bitfield** [comment]
I noticed that too, but I couldn't find any information about what `brody715`'s extension does that yours doesn't, @twpayne. According to the comments on that issue, it sounds like the answer is 'nothing'. You mentioned some suggestions from @myitcv—what were they?

**Comment by twpayne** [comment]
The observation that @myitcv made is that `.txtar` files are in txtar format (which is a comment followed by a bunch of inline files with separators between them). For testscript, the comment happens to be interpreted by testscript as a script, but the format of the file is txtar, not testscript. twpayne/vscode-testscript does not make this distinction, whereas (if I understood it correctly), brody715/vscode-txtar does. vscode-txtar also supports a couple of extra formats for the inline files (including CUE) and has a more automated way of adding more formats.

**Comment by bitfield** [comment]
It looks to me as though `vscode-testscript` highlights the script, too—at least, that's what I'm seeing.

**Comment by twpayne** [comment]
Yeah, that's right: they both highlight the testscript. The difference is more in the structure of the code: vscode-txtar explicitly makes the distinction between the txtar format and the testscript syntax, whereas vscode-testscript does not make the distinction and mixes everything together in the syntax. The end results for the VSCode users are extremely similar, however.
