### ISSUE TITLE
testscript: add support for file modes to txtar?

### ISSUE THREAD

**Issue by twpayne** [rogpeppe/go-internal#99]
Currently the txtar format only allows regular files to be created. Sometimes it's useful to include executable files (e.g. shell scripts) or private files (e.g. fake private keys) in tests. At the moment, this can only be done with `chmod`:

```
chmod 755 bin/hello.sh
chmod 600 home/user/.password

-- bin/hello.sh --
#!/bin/sh
echo "Hello, world!"
-- home/user/.password --
correcthorsebatterystaple
```

This requires repetition of the filename and extra code.

It would be nice if the file mode could be specified in the txtar section, something like:

```
-- bin/hello.sh -- mode 755 --
#!/bin/sh
echo "Hello, world!"
-- home/user/.password -- mode 600 --
correcthorsebatterystaple
```

This can easily be done in a backwards-compatible way. There are, of course, many possible syntaxes, and I'm happy with any that work.

However, the [`golang.org/x/tools/txtar` documentation](https://pkg.go.dev/golang.org/x/tools/txtar?tab=doc) explicitly states (emphasis added):

> Non-goals include being a completely general archive format, storing binary data, **storing file modes**, storing special files like symbolic links, and so on.

`testscript` is a particularly useful package, with applications well beyond testing the `go` command.

Would a PR that adds support for file modes to txtar files be accepted?

**Comment by twpayne** [comment]
FWIW, I've worked around this issue in my test scripts by adding an explicit `Setup` function that fixes permissions in the files created from txtar archives, e.g. https://github.com/twpayne/chezmoi/pull/744/commits/53f24c951c6c38eac1da65f7613589febb45630c.

**Comment by myitcv** [comment]
FWIW I think this is the "correct" way to do things given the intended limitations of `testscript`. We have to apply similar workarounds when using txtar within txtar:

https://github.com/rogpeppe/go-internal/blob/master/testscript/testdata/testscript_update_script_quote.txt

> This can easily be done in a backwards-compatible way.

Can it be done in a backwards compatible way?

> The file marker line must begin with the three-byte sequence "-- " and end with the three-byte sequence " --", but the enclosed file name can be surrounding by additional white space, all of which is stripped.

**Comment by mvdan** [comment]
Another reason why I think testscript shouldn't try to handle this automatically is that permissions are inherently not very portable. Should `755` error on windows, or silently only apply `0200` on Windows?

**Comment by twpayne** [comment]
> Can it be done in a backwards compatible way?

OK, if people are creating files where `"-- "` or `" --"` is part of the filename then I agree it's not 100% backwards compatible, but probably good enough in practice.

> Another reason why I think testscript shouldn't try to handle this automatically is that permissions are inherently not very portable.

That's a very good point.

So it looks like there are already good enough workarounds for this, it can't be done in a strictly 100% backwards-compatible way, and it's problematic on Windows. Sounds like this issue should be closed :) Thanks for considering it :)
